### ISSUE TITLE
capital key in json produces underscored variables in env

### ISSUE THREAD

**Issue by rohitshetty** [ralucas/json-to-env#1]
```
{
"TEST":"value" 
}


produces
{
export T_E_S_T = value

}
```

Is this intended? If this is the bug I would be happy to fix and make a PR

**Comment by ralucas** [comment]
Interesting.  No that was not intended.  I would welcome a PR or I can fix it as well.  Let me know.

**Comment by ralucas** [comment]
Here's the culprit:
```
  function camelToSnakeCase(str) {
    return str.replace(/[A-Z]/g, '\_$&');
  }
```

**Comment by ralucas** [comment]
I haven't really tested this, but perhaps a solution:
```
function isCamelCase(str) {
  return !!str.match(/^[a-z]+[A-Z]/)
}

function camelToSnakeCase(str) {
    if ( isCamelCase(str) ) return str.replace(/[A-Z]/g, '\_$&');
    return str;
  }
```
Thoughts?

**Comment by rohitshetty** [comment]
This looks like should do the job. Thanks! Would this be merged with master soon?

**Comment by ralucas** [comment]
Yes, I'll get it in master now

**Comment by ralucas** [comment]
Okay version 0.0.8 reflects these changes.  Let me know if you're still seeing this issue, but I'm going to close this for now.
