### ISSUE TITLE
npm install doesnt work

### ISSUE THREAD

**Issue by rohitshetty** [ralucas/json-to-env#2]
npm install doesnt install complete module.

**Comment by ralucas** [comment]
Hmm, I did a horrible job here, my apologies.  Let me look into this.

**Comment by rohitshetty** [comment]
No worries :) Thank you for your time and contribution :)

**Comment by rohitshetty** [comment]
Any idea when can I expect this to be available on npm?

**Comment by ralucas** [comment]
Yes, just give me maybe until tomorrow at the latest and I'll have it for you

**Comment by ralucas** [comment]
Ok, thanks for catching this.  This should now be fixed in version 0.0.8
