### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by phil-warner** [ralucas/json-to-env#3]
Hi

After I install the package (using 'sudo npm i json-to-env -g') and try to run it (using 'json-to-env app.json app.config') I get "command not found". I'm running from the directory in which app.json lives.

**Comment by ralucas** [comment]
Hi, yes this is an issue.  I will fix this ASAP and should have a build for you later today.  My apologies.

Richard

**Comment by phil-warner** [comment]
Thanks Richard! No rush.

Phil

**Comment by phil-warner** [comment]
Did you get a chance to get to this?

**Comment by ZebGirouard** [comment]
Womp.  Another project forgotten.  A great idea--hopefully someone with time and motivation sees this thread, and decides to take their own stab at it.  For now, R.I.P. `json-to-env`.

**Comment by ralucas** [comment]
Should be fixed.
